version: 1.3.{build}-{branch}

image: Visual Studio 2015

cache:
    - C:\MumbleBuild\cache -> appveyor.yml

clone_folder: C:\MumbleBuild\mumble

environment:
    MUMBLE_BUILDSCRIPT: 1.3.x/mumble-win64-static.cmd
    MUMBLE_ENVIRONMENT_VERSION: win64-static-no-ltcg-1.3.x-2017-02-02-ec94ddb-790
    MUMBLE_ENVIRONMENT_SOURCE:
        secure: UunKleXPYa2aQjF0WzUaM7mUVN/pIY4BBHcWSbwWolw=
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -mx0  # Do not compress cache. Env. is already a 7z.

install:
  - "git submodule --quiet update --init --recursive"
  - "powershell ./appveyor-install-environment.ps1"

build_script:
  - "powershell ./appveyor-build.ps1"
